version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python3 -m pip install --upgrade pip
      - pip3 install cfn-lint
      - gem install cfn-nag
  build:
    commands:
      - echo "Validating CloudFormation template"
      - cfn-lint ./templates/**/*.yml
      - echo "Running cfn-nag..."
      - cfn_nag_scan --input-path ./templates

artifacts:
  discard-paths: yes
  files:
    - templates/template.yml

cache:
  paths:
    - "/root/.cache/pip/**/*"
