AWSTemplateFormatVersion: "2010-09-09"

Description: This stack creates a backup vault that is shared with other accounts, allowing one source account to copy backups into the vault and other accounts to copy backups out of the vault. Backups stored in this vault cannot be deleted manually and are kept until their retention period expires.

Parameters:
  VaultWriterAccountId:
    Description: AWS Account ID of an account that should be allowed to copy backups into this vault.
    Type: String
    Default: ""

  VaultReaderAccountIds:
    Description: AWS Account IDs of accounts that should be allowed to copy backups from this vault.
    Type: List<String>

Resources:
  BackupVault:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Backup::LogicallyAirGappedBackupVault
    Properties:
      AccessPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowBackupCopyFromAccount
            Effect: Allow
            Principal:
              AWS: !Ref VaultWriterAccountId
            Action:
              - backup:CopyIntoBackupVault
            Resource: '*'
          - Sid: AllowCopyFromBackupVaultToReadAccounts
            Effect: Allow
            Principal:
              AWS: !Ref VaultReaderAccountIds
            Action:
              - backup:CopyFromBackupVault
            Resource: '*'
      BackupVaultName: !Sub ${AWS::StackName}-backup-vault2 # FIXME: Unique name
      MaxRetentionDays: 14 # FIXME: Low value for testing, should be a year or more
      MinRetentionDays: 7
      VaultType: LOGICALLY_AIR_GAPPED_BACKUP_VAULT

  BackupVaultShareWriteAccount:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: !Sub ${AWS::StackName}-Writer
      Principals:
        - !Ref VaultWriterAccountId
      ResourceArns:
        - !GetAtt BackupVault.BackupVaultArn

  BackupVaultShareReadAccounts:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: !Sub ${AWS::StackName}-Readers
      Principals: !Ref VaultReaderAccountIds
      ResourceArns:
        - !GetAtt BackupVault.BackupVaultArn
