AWSTemplateFormatVersion: "2010-09-09"

Description: This stack creates a logically-air gapped backup vault and supporting resources, intended to be used for storing copies of backups for all services in a given environment.

Parameters:
  Environment:
    Description: Deployment environment
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - test
      - prod

  OwnerAccountId:
    Description: AWS Account ID of the account that can write to the backup vault
    Type: String
    Default: "750639270376" # FIXME: Account ID of sandbox account, just to test

Resources:
  BackupVault:
    Type: AWS::Backup::LogicallyAirGappedBackupVault
    Properties:
      AccessPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowBackupCopyFromAccount
            Effect: Allow
            Principal:
              AWS: !Ref OwnerAccountId
            Action:
              - backup:CopyIntoBackupVault
            Resource:
              - !Sub arn:aws:backup:${AWS::Region}:${OwnerAccountId}:backup-vault/*
              - !Sub arn:aws:backup:${AWS::Region}:${OwnerAccountId}:recovery-point/*
      BackupVaultName: !Sub ${AWS::StackName}-backup-vault2 # FIXME: Unique name
      MaxRetentionDays: 14 # FIXME: Low value for testing, should be a year or more
      MinRetentionDays: 2
      VaultType: LOGICALLY_AIR_GAPPED_BACKUP_VAULT

  BackupVaultShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: !Sub ${AWS::StackName}
      Principals:
        - !Ref OwnerAccountId
      ResourceArns:
        - !GetAtt BackupVault.BackupVaultArn

Outputs:
  Tmp:
    Description: Name of the environment
    Value: !Ref Environment
