AWSTemplateFormatVersion: "2010-09-09"

Description: This stack creates a logically-air gapped backup vault and supporting resources, intended to be used for storing copies of backups for all services in a given environment.

Parameters:
  Environment:
    Description: Deployment environment
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - test
      - prod

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: !Sub Example bucket for the ${Environment} environment
    Properties:
      BucketName: !Sub ${AWS::StackName}-example-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AutoArchive
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: INTELLIGENT_TIERING

  BackupVault:
    Type: AWS::Backup::LogicallyAirGappedBackupVault
    Properties:
      BackupVaultName: !Sub ${AWS::StackName}-backup-vault
      EncryptionKeyArn: STRING
      MaxRetentionDays: 14 # FIXME: Low value for testing, should be a year or more
      MinRetentionDays: 7
      VaultType: LOGICALLY_AIR_GAPPED_BACKUP_VAULT

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref DataBucket

  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt DataBucket.Arn
