AWSTemplateFormatVersion: "2010-09-09"

Description: This stack creates a backup vault that is shared with other accounts, allowing one source account to copy backups into the vault and other accounts to copy backups out of the vault. Backups stored in this vault cannot be deleted manually and are kept until their retention period expires.

Parameters:
  VaultWriterAccountId:
    Description: AWS Account ID of an account that should be allowed to copy backups into this vault.
    Type: String
    Default: ""

  VaultReaderAccountIds:
    Description: AWS Account IDs of accounts that should be allowed to copy backups from this vault.
    Type: CommaDelimitedList

  VaultMinRetentionDays:
    Description: Minimum number of days to retain backups in the vault.
    Type: Number
    Default: 7
    MinValue: 7

  VaultMaxRetentionDays:
    Description: Maximum number of days to retain backups in the vault.
    Type: Number
    Default: 365
    MinValue: 14

Resources:
  BackupVault:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::Backup::LogicallyAirGappedBackupVault
    Properties:
      AccessPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAccessFromVaultWriter
            Effect: Allow
            Principal:
              AWS: !Ref VaultWriterAccountId
            Action:
              - backup:CopyIntoBackupVault
            Resource: '*'

          # Note: This policy is too permissive and duplicates the above policy.
          # This is because of a limitation in allowed actions for cross-account sharing,
          # which only allows the CopyIntoBackupVault action to be shared with other accounts.
          # As this vault type does not allow deletion of backups, this is acceptable for now.
          - Sid: AllowAccessFromVaultReaders
            Effect: Allow
            Principal:
              AWS: !Ref VaultReaderAccountIds
            Action:
              - backup:CopyIntoBackupVault
            Resource: '*'
      BackupVaultName: !Sub ${AWS::StackName}-vault
      MaxRetentionDays: !Ref VaultMaxRetentionDays
      MinRetentionDays: !Ref VaultMinRetentionDays
      VaultType: LOGICALLY_AIR_GAPPED_BACKUP_VAULT

  BackupVaultShareWriteAccount:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: !Sub ${AWS::StackName}-Writer
      Principals:
        - !Ref VaultWriterAccountId
      ResourceArns:
        - !GetAtt BackupVault.BackupVaultArn

  BackupVaultShareReadAccounts:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: !Sub ${AWS::StackName}-Readers
      Principals: !Ref VaultReaderAccountIds
      ResourceArns:
        - !GetAtt BackupVault.BackupVaultArn
