AWSTemplateFormatVersion: "2010-09-09"

Description: This stack creates a logically-air gapped backup vault and supporting resources, intended to be used for storing copies of backups for all services in a given environment.

Parameters:
  TargetAccountId:
    Description: AWS Account ID of the account that can write to the backup vault
    Type: String
    Default: "12345"

Resources:
  BackupVault:
    Type: AWS::Backup::LogicallyAirGappedBackupVault
    Properties:
      AccessPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowBackupCopyFromAccount
            Effect: Allow
            Principal:
              AWS: !Ref TargetAccountId
            Action:
              - backup:CopyIntoBackupVault
            Resource: '*'
      BackupVaultName: !Sub ${AWS::StackName}-backup-vault2 # FIXME: Unique name
      MaxRetentionDays: 14 # FIXME: Low value for testing, should be a year or more
      MinRetentionDays: 7
      VaultType: LOGICALLY_AIR_GAPPED_BACKUP_VAULT

  BackupVaultShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: !Sub ${AWS::StackName}
      Principals:
        - !Ref TargetAccountId
      ResourceArns:
        - !GetAtt BackupVault.BackupVaultArn
